[project]
name = 'health-ownership'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.emergency-access]
path = 'contracts/emergency-access.clar'
clarity_version = 3
epoch = 3.1

[contracts.health-ownership]
path = 'contracts/health-ownership.clar'
clarity_version = 3
epoch = 3.1

[contracts.health-marketplace]
path = 'contracts/health-marketplace.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
